eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka1:3001/eureka,http://eureka2:3002/eureka
  instance:
    hostname: eureka
    prefer-ip-address: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
server:
  port: 1000
spring:
  application:
    name: eurekaServer
  profiles:
    active: dev
